#!/usr/bin/sh

#find $HOME -not -path '*/\.*' -type f  -name "*.pdf" | rofi -dmenu -i -p "Open PDF" | sed -e 's/.*/"&"/' | xargs zathura
find $HOME/Documents -type f  -name "*.pdf" | rofi -dmenu -i -p "Open PDF" | sed -e 's/.*/"&"/' | xargs zathura

#find $HOME -not -path '*/\.*' -type f  -name "*.pdf" | fzf | sed -e 's/.*/"&"/' | xargs zathura
